<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="VerifyHomePageContent"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="43.647">
  <properties />
            <testcase name="Step01_NavigeteToURL" time="43.647" classname="comcast.test.homepage.VerifyHomePageContent">
                <failure type="java.lang.AssertionError"
                  message="Failed to navigate to Watchable Mobile web Home Page expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: Failed to navigate to Watchable Mobile web Home Page expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  comcast.common.asserts.Assertions.assertWatchableTitle(Assertions.java:26)
  comcast.test.homepage.VerifyHomePageContent.Step01_NavigeteToURL(VerifyHomePageContent.java:30)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.TestNG.privateMain(TestNG.java:1364)
  org.testng.TestNG.main(TestNG.java:1333)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
